### PR TITLE
Use tx-power flag when updating cell

### PR DESCRIPTION
**Pull request by jmajnert**

### CODE REVIEW

**Review by alex-onf — APPROVED** [review]
LGTM

@woojoong88, could you please approve?

**Review by adibrastegarnia — APPROVED** [review]

**Review by woojoong88 — APPROVED** [review]

**Comment by alex-onf** [comment]
@adibrastegarnia, @woojoong88, how can we merge this change? I see that the Jenkins check is stuck since 1 week.

**Comment by adibrastegarnia** [comment]
> @adibrastegarnia, @woojoong88, how can we merge this change? I see that the Jenkins check is stuck since 1 week.

You should check with ONF folks for CI jobs.

**Comment by woojoong88** [comment]
Yeah please check it with David.

**Comment by gab-arrobo** [comment]
ok to test

**Comment by gab-arrobo** [comment]
Merging this PR given that it is already approved

**Comment by alex-onf** [comment]
> > @adibrastegarnia, @woojoong88, how can we merge this change? I see that the Jenkins check is stuck since 1 week.
> 
> @alex-onf you need to let Jenkins know that you are ok testing it (i.e., using key words `ok to test`), otherwise, Jenkins will not run any job(s)

Thank you so much @gab-arrobo! I was not aware about this, good to know!

**Pull request merged**
