### PR TITLE
Releasing v0.7.16

### PR DESCRIPTION
**Pull request by tomikazi**

### CODE REVIEW

**Review by adibrastegarnia — APPROVED** [review]

**Comment by tomikazi** [comment]
retest this please

**Review by ray-milkey — APPROVED** [review]

**Comment by ray-milkey** [comment]
retest this please

**Review by teone — APPROVED** [review]

**Comment by teone** [comment]
recheck

**Comment by ray-milkey** [comment]
please retest this

**Comment by tomikazi** [comment]
Thanks all for working out the onf/cla quirk.

**Pull request merged**
